import type { Metadata } from "next"
import { Caveat, Montserrat } from "next/font/google"

import "./globals.css"
import { cn } from "@/lib/utils"
import { ScrollArea } from "@/components/ui/scroll-area"

const montserrat = Montserrat({
  subsets: ["latin", "cyrillic"],
  variable: "--font-montserrat",
})

const caveat = Caveat({
  subsets: ["latin", "cyrillic"],
  variable: "--font-caveat",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          montserrat.variable,
          caveat.variable,
          "flex min-h-screen flex-col antialiased",
        )}
      >
        <ScrollArea className="relative flex h-dvh w-full flex-col">
          {children}
        </ScrollArea>
      </body>
    </html>
  )
}
